app:
  name: ui
  image:
    repository: 'onecx/onecx-parameter-ui'
  routing:
    enabled: true
    path: /mfe/parameter/
  
  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: "./OneCXParameterModule"
          description: "OneCX Parameter UI"
          note: "OneCX Parameter UI auto import via operator"
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-parameter
          tagName: ocx-parameter-component
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          PARAMETER:
            DELETE: Delete parameter
            EDIT: Edit parameter
            VIEW: View parameter
            SEARCH: Search parameter
# PIPE Config
